### ISSUE TITLE
Cannot use cucim for patch extraction with ndpi files

### ISSUE THREAD

**Issue by OliS1311** [TIO-IKIM/CellViT#70]
I am able to use cucim to for patch extraction with the example svs file specified and with others from TCGA. When I try to use cucim for for my ndpi files, I get an error saying that a plugin for handling them cannot be found. I'm still able to perform patch extraction successfully if I change the config file so that cucim isn't used (i.e. set hardware_selection: openslide) but would obviously like to be able to perform this step faster with cucim.

`python3 ./preprocessing/patch_extraction/main_extraction.py --config ./example/preprocessing_example_filename.yaml`

```
2024-10-30 16:05:12,045 [INFO] - Using CuCIM
2024-10-30 16:05:12,046 [INFO] - Data store directory: /home/username/CellViT-main/example/output/preprocessing_3
2024-10-30 16:05:12,046 [INFO] - Images found: 1
2024-10-30 16:05:12,046 [INFO] - Annotations found: 0
2024-10-30 16:05:12,046 [INFO] - Removing complete dataset! This may take a while.
2024-10-30 16:05:12,047 [INFO] - **************************************************************************************
2024-10-30 16:05:12,047 [INFO] - 1/1: filename.ndpi
2024-10-30 16:05:12,047 [INFO] - Computing patches for filename.ndpi
Traceback (most recent call last):
  File "/home/username/CellViT-main/./preprocessing/patch_extraction/main_extraction.py", line 33, in <module>
    slide_processor.sample_patches_dataset()
  File "/home/username/CellViT-main/preprocessing/patch_extraction/src/patch_extraction.py", line 345, in sample_patches_dataset
    ) = self._prepare_wsi(wsi_file)
  File "/home/username/CellViT-main/preprocessing/patch_extraction/src/patch_extraction.py", line 592, in _prepare_wsi
    slide_cu = self.image_loader(str(wsi_file))
ValueError: Cannot find a plugin to handle '/home/username/CellViT-main/example/filename.ndpi'!
```

**Comment by FabianHoerst** [comment]
Hello,

I am not sure if CuCIM is compatible with ndpi files. Thus, i would stick to openslide for this matter.

Best, Fabian
