### ISSUE TITLE
 Issue with VIT-SAM-H weights during inference on fold1

### ISSUE THREAD

**Issue by CYYJL** [TIO-IKIM/CellViT#75]
I am encountering an issue while performing inference on fold1 using the VIT-SAM-H weights you provided. I received the following error:

```
Traceback (most recent call last):
  File "/home/Lablin/501Lab/YJL/CellViT-main/vio.py", line 112, in <module>
    vit_samh_batch_metrics, vit_samh_scores = inference.calculate_step_metric(vit_samh_predictions, vit_samh_gt, image_names)
  File "/home/Lablin/501Lab/YJL/CellViT-main/cell_segmentation/inference/inference_mul_cellvit_experiment_pannuke.py", line 1223, in calculate_step_metric
    paired_all = np.concatenate(paired_all, axis=0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate
```

The error occurs during the calculation of detection metrics. Could you please advise on how to resolve this issue?

Thank you for your help
Best wish
CYYJL

**Comment by FabianHoerst** [comment]
Hi, It seems like the error occurs in files you coded yourself. Therefore, unfortunately, I cannot assist you with that. I am very sorry.
